In [30]:
%pip install requests

Requirement already satisfied: requests in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from requests) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\lenovo\onedrive\onedrive - national college of ireland\machine_learning_project\.venv\lib\site-packages (from requests) (2026.10.23)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)   # show long text in full

file_path = r'C:\Users\LENOVO\OneDrive\OneDrive - National College of Ireland\Machine_learning_Project\dataSet\raw_dataset\Housing_dataset\Housing-plan\planning_applications_national.csv'

In [32]:
planning = pd.read_csv(file_path, low_memory=False)

print(planning.shape)   # (rows, columns)
planning.head()

(225141, 37)

,OBJECTID,PlanningAuthority,ApplicationNumber,DevelopmentDescription,DevelopmentAddress,DevelopmentPostcode,ITMEasting,ITMNorthing,ApplicationStatus,ApplicationType,ApplicantForename,ApplicantSurname,ApplicantAddress,Decision,LandUseCode,AreaofSite,NumResidentialUnits,OneOffHouse,FloorArea,ReceivedDate,WithdrawnDate,DecisionDate,DecisionDueDate,GrantDate,ExpiryDate,AppealRefNumber,AppealStatus,AppealDecision,AppealDecisionDate,AppealSubmittedDate,FIRequestDate,FIRecDate,LinkAppDetails,OneOffKPI,ETL_DATE,SiteId,ORIG_FID
0,632,Carlow County Council,21393,"Permission is sought for vehicular entrance in to zoned lands (to replace agricultural entrance / repositioning previously granted vehicular entrance), front boundary treatment and associated site...","Dublin Road , Pollerton Big , CarlowTown",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,NaN,NaN,NaN,REFUSED,,NaN,0.0,,0.0,1634256000000,NaN,1.666138e+12,1.666224e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.638835e+12,1.661472e+12,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/21393/0,No,1792454400000,NaN,NaN
1,886,Carlow County Council,2445,"alterations and additions to an existing single storey dwelling house, namely erection of a single storey extension to the rear of existing dwelling, removal of existing lean-to extension to side ...","Ballyveal , Ballon , Co. Carlow",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,NaN,NaN,NaN,CONDITIONAL,,NaN,1.0,,10.0,1729123200000,NaN,1.733702e+12,1.733875e+12,1.737331e+12,1.895011e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2445/0,No,1792454400000,NaN,NaN
2,887,Carlow County Council,2446,"construct a single-storey domestic dwelling, with on-site wastewater treatment system compliant with current EPA requirement, detached domestic garage, bored well, new entrance/access from adjoini...","Ballypierce , Kildavin , Co.Carlow",NaN,NaN,NaN,WITHDRAWN,PERMISSION,NaN,NaN,NaN,NaN,,NaN,0.0,,0.0,1730160000000,1.730765e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2446/0,No,1792454400000,NaN,NaN
3,888,Carlow County Council,2447,"the construction of a one and a half storey extension to side of existing dwelling, attic conversion and to include minor internal and external alterations to accommodate same and all associated s...","Rickettstown , Rathvilly , Co. Carlow",NaN,NaN,NaN,INCOMPLETED APPLICATION,PERMISSION,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,1730332800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2447/0,No,1792454400000,NaN,NaN
4,889,Carlow County Council,2448,the erection of two houses and two garages,"Burrin Road , Paupish Lane , Carlow",NaN,NaN,NaN,INCOMPLETED APPLICATION,PERMISSION,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,1731456000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2448/0,No,1792454400000,NaN,NaN

In [33]:
print('Number of columns:', len(planning.columns))
planning.dtypes

Number of columns: 37

OBJECTID                    int64
PlanningAuthority             str
ApplicationNumber             str
DevelopmentDescription        str
DevelopmentAddress            str
DevelopmentPostcode           str
ITMEasting                float64
ITMNorthing               float64
ApplicationStatus             str
ApplicationType               str
ApplicantForename         float64
ApplicantSurname          float64
ApplicantAddress          float64
Decision                      str
LandUseCode                   str
AreaofSite                float64
NumResidentialUnits       float64
OneOffHouse                   str
FloorArea                 float64
ReceivedDate                int64
WithdrawnDate             float64
DecisionDate              float64
DecisionDueDate           float64
GrantDate                 float64
ExpiryDate                float64
AppealRefNumber               str
AppealStatus                  str
AppealDecision                str
AppealDecisionDate        float64
AppealSubmittedDate       float64
FIRequestDate             float64
FIRecDate                 float64
LinkAppDetails                str
OneOffKPI                     str
ETL_DATE                    int64
SiteId                    float64
ORIG_FID                  float64
dtype: object

## Step 4: Converting date columns
Dates are stored as form of large numbers, which is how ArcGIS saves them.
We convert them into normal dates type. easy to undersatnd and read

In [34]:
date_columns = ['ReceivedDate', 'WithdrawnDate', 'DecisionDate', 'DecisionDueDate',
                'GrantDate', 'ExpiryDate', 'AppealDecisionDate', 'AppealSubmittedDate',
                'FIRequestDate', 'FIRecDate', 'ETL_DATE']

for col in date_columns:
    planning[col] = pd.to_datetime(planning[col], unit='ms', errors='coerce')

planning[['ApplicationNumber', 'ReceivedDate', 'DecisionDate', 'GrantDate']].head()

  ApplicationNumber ReceivedDate DecisionDate  GrantDate
0             21393   2021-10-15   2022-10-19        NaT
1              2445   2024-10-17   2024-12-09 2025-01-20
2              2446   2024-10-29          NaT        NaT
3              2447   2024-10-31          NaT        NaT
4              2448   2024-11-13          NaT        NaT

##Step 5: Check missing values (% of rows empty in each column)

In [35]:
missing = planning.isnull().mean() * 100
missing.round(1).sort_values(ascending=False)

ApplicantAddress          100.0
ApplicantForename         100.0
ApplicantSurname          100.0
ITMNorthing               100.0
ITMEasting                100.0
ORIG_FID                  100.0
AppealStatus               99.5
DevelopmentPostcode        98.9
AppealDecisionDate         96.4
AppealDecision             96.3
WithdrawnDate              95.9
AppealRefNumber            95.9
AppealSubmittedDate        95.9
SiteId                     92.2
FIRecDate                  75.8
FIRequestDate              72.8
OneOffHouse                58.0
LandUseCode                56.4
ExpiryDate                 53.9
GrantDate                  38.0
OneOffKPI                  32.8
FloorArea                  26.6
NumResidentialUnits        26.4
AreaofSite                 22.4
Decision                   20.9
DecisionDate               20.4
DecisionDueDate            15.5
LinkAppDetails             12.5
ApplicationStatus           1.6
ApplicationType             0.1
DevelopmentAddress          0.0
ApplicationNumber           0.0
PlanningAuthority           0.0
OBJECTID                    0.0
DevelopmentDescription      0.0
ReceivedDate                0.0
ETL_DATE                    0.0
dtype: float64

### Step 6: Look at the key columns
- Which councils are in the data?
- What decisions were made?
- What is the status of each application?
- What type of application is it?

In [36]:
print(planning['PlanningAuthority'].value_counts(), '\n')
print(planning['Decision'].value_counts(dropna=False), '\n')
print(planning['ApplicationStatus'].value_counts(), '\n')
print(planning['ApplicationType'].value_counts())

PlanningAuthority
Cork County Council                      20934
Dublin City Council                      18314
Donegal County Council                   13785
Galway County Council                    11574
Meath County Council                     10613
Dun Laoghaire Rathdown County Council     9799
Kildare County Council                    9763
Wexford County Council                    9604
Tipperary County Council                  8926
Fingal County Council                     8901
Wicklow County Council                    8259
Kerry County Council                      8056
Limerick County Council                   7903
Mayo County Council                       7530
Clare County Council                      7040
Louth County Council                      6494
Waterford City and County Council         6414
South Dublin County Council               6337
Kilkenny County Council                   5295
Laois County Council                      5238
Offaly County Council                     4376
Cavan County Council                      4174
Roscommon County Council                  4096
Westmeath County Council                  3805
Monaghan County Council                   3753
Cork City Council                         3309
Sligo County Council                      2916
Carlow County Council                     2791
Galway City Council                       2004
Longford County Council                   1772
Leitrim County Council                    1366
Name: count, dtype: int64

Decision
CONDITIONAL                                               108867
NaN                                                        47016
REFUSED                                                    13605
GRANT PERMISSION                                           12433
Granted (Conditional)                                       6392
                                                           ...
Decision Quashed By High Court                                 1
Section 179A Derogation Withered                               1
Part 8 Rejected by Council                                     1
Grant Outdoor Event Licence                                    1
Grant Retention & Grant Permission & Refuse Permission         1
Name: count, Length: 161, dtype: int64

ApplicationStatus
APPLICATION FINALISED                                 121079
INCOMPLETED APPLICATION                                26219
Decision Notice Issued                                 16611
WITHDRAWN                                               6700
Final Grant                                             6570
                                                       ...
Validation                                                 1
CSAI Request Approved                                      1
CAI Received                                               1
CAI Requested                                              1
AI Request Approved                                        1
Name: count, Length: 131, dtype: int64

ApplicationType
PERMISSION                                                130516
Permission                                                 35591
RETENTION                                                  29378
Permission                                                  7248
Permission                                                  5081
                                                           ...
Part X (public consultation)                                   1
Continuation of Use                                            1
Perm. following Grant of Outline Perm.                         1
Approval                                                       1
Application Under Part 10                                      1
Name: count, Length: 68, dtype: int64

## Step 8: Look at the text column (DevelopmentDescription)
The project brief needs text data averaging **at least 40 words per row**.

In [37]:
# Show 5 example descriptions
for text in planning['DevelopmentDescription'].head(5):
    print('-', text)
    print()

# Count the words in each description
planning['word_count'] = planning['DevelopmentDescription'].fillna('').str.split().str.len()

print('Average words per description:', round(planning['word_count'].mean(), 1))
print('Median words per description: ', planning['word_count'].median())

- Permission is sought for vehicular entrance in to zoned lands (to replace agricultural entrance / repositioning previously granted vehicular entrance), front boundary treatment and associated site works.  A Natura Impact Statement / flood risk have been prepared in respect of the proposed development.

- alterations and additions to an existing single storey dwelling house, namely erection of a single storey extension to the rear of existing dwelling, removal of existing lean-to extension to side of dwelling and removal of garage at rear of existing dwelling, internal alterations, and all associated ancillary site works

- construct a single-storey domestic dwelling, with on-site wastewater treatment system compliant with current EPA requirement, detached domestic garage, bored well, new entrance/access from adjoining public road and all ancillary site works

- the construction of a one and a half storey extension to side of existing dwelling, attic conversion and to include minor internal and external alterations to accommodate same and all associated site works

- the erection of two houses and two garages

Average words per description: 41.3
Median words per description:  27.0

In [38]:
planning.head()

,OBJECTID,PlanningAuthority,ApplicationNumber,DevelopmentDescription,DevelopmentAddress,DevelopmentPostcode,ITMEasting,ITMNorthing,ApplicationStatus,ApplicationType,ApplicantForename,ApplicantSurname,ApplicantAddress,Decision,LandUseCode,AreaofSite,NumResidentialUnits,OneOffHouse,FloorArea,ReceivedDate,WithdrawnDate,DecisionDate,DecisionDueDate,GrantDate,ExpiryDate,AppealRefNumber,AppealStatus,AppealDecision,AppealDecisionDate,AppealSubmittedDate,FIRequestDate,FIRecDate,LinkAppDetails,OneOffKPI,ETL_DATE,SiteId,ORIG_FID,word_count
0,632,Carlow County Council,21393,"Permission is sought for vehicular entrance in to zoned lands (to replace agricultural entrance / repositioning previously granted vehicular entrance), front boundary treatment and associated site...","Dublin Road , Pollerton Big , CarlowTown",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,NaN,NaN,NaN,REFUSED,,NaN,0.0,,0.0,2021-10-15,NaT,2022-10-19,2022-10-20,NaT,NaT,NaN,NaN,NaN,NaT,NaT,2021-12-07,2022-08-26,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/21393/0,No,2026-10-20,NaN,NaN,43
1,886,Carlow County Council,2445,"alterations and additions to an existing single storey dwelling house, namely erection of a single storey extension to the rear of existing dwelling, removal of existing lean-to extension to side ...","Ballyveal , Ballon , Co. Carlow",NaN,NaN,NaN,APPLICATION FINALISED,PERMISSION,NaN,NaN,NaN,CONDITIONAL,,NaN,1.0,,10.0,2024-10-17,NaT,2024-12-09,2024-12-11,2025-01-20,2030-01-19,NaN,NaN,NaN,NaT,NaT,NaT,NaT,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2445/0,No,2026-10-20,NaN,NaN,49
2,887,Carlow County Council,2446,"construct a single-storey domestic dwelling, with on-site wastewater treatment system compliant with current EPA requirement, detached domestic garage, bored well, new entrance/access from adjoini...","Ballypierce , Kildavin , Co.Carlow",NaN,NaN,NaN,WITHDRAWN,PERMISSION,NaN,NaN,NaN,NaN,,NaN,0.0,,0.0,2024-10-29,2024-11-05,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaT,NaT,NaT,NaT,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2446/0,No,2026-10-20,NaN,NaN,31
3,888,Carlow County Council,2447,"the construction of a one and a half storey extension to side of existing dwelling, attic conversion and to include minor internal and external alterations to accommodate same and all associated s...","Rickettstown , Rathvilly , Co. Carlow",NaN,NaN,NaN,INCOMPLETED APPLICATION,PERMISSION,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,2024-10-31,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaT,NaT,NaT,NaT,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2447/0,No,2026-10-20,NaN,NaN,33
4,889,Carlow County Council,2448,the erection of two houses and two garages,"Burrin Road , Paupish Lane , Carlow",NaN,NaN,NaN,INCOMPLETED APPLICATION,PERMISSION,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,2024-11-13,NaT,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaT,NaT,NaT,NaT,http://www.eplanning.ie/CarlowCC/AppFileRefDetails/2448/0,No,2026-10-20,NaN,NaN,8